const SECTIONS = [
  {
    num: '1',
    title: 'Acceptance of Terms',
    body: 'By accessing or using DeepNano ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service.',
  },
  {
    num: '2',
    title: 'Description of Service',
    body: 'The Service provides cloud-based AI coding agents. Users can connect repositories, run agents (including Bring Your Own Key / BYOK models), execute tasks, and manage code changes. Features include isolated environments, real-time collaboration, and GitHub integration.',
  },
  {
    num: '3',
    title: 'Eligibility',
    body: 'You must be at least 18 years old and have authority to bind your organization if using on behalf of one.',
  },
  {
    num: '4',
    title: 'Accounts',
    body: 'You are responsible for maintaining account security. Notify us immediately of any unauthorized access.',
  },
  {
    num: '5',
    title: 'Bring Your Own Keys (BYOK) and AI Usage',
    body: [
      'You may provide API keys for supported models. You are solely responsible for all charges incurred with your providers.',
      'We do not store or have access to your API keys beyond secure transmission and use.',
      'AI outputs are generated by third-party models. We make no warranties regarding accuracy, completeness, or suitability of generated code.',
    ],
  },
  {
    num: '6',
    title: 'User Content and Code',
    body: [
      'You retain ownership of your code and data ("User Content"). By using the Service, you grant us a limited license to host, process, and display it as necessary to provide the Service.',
      'Agents may generate code; you are responsible for reviewing, testing, and deploying it.',
    ],
  },
  {
    num: '7',
    title: 'Acceptable Use',
    body: 'You agree not to: use the Service for illegal purposes or to violate laws; attempt to access other users\' data or environments; overload systems or engage in abusive automation; share API keys or access credentials; upload malicious code or use agents to harm systems.',
  },
  {
    num: '8',
    title: 'GitHub Integration',
    body: 'You authorize us to access your GitHub repositories as permitted by your permissions. We respect GitHub\'s terms and your privacy settings.',
  },
  {
    num: '9',
    title: 'Fees and Billing',
    body: [
      'Paid plans are billed monthly/annually.',
      'No refunds except as required by law. Downgrades take effect at next cycle.',
      'We may change pricing with notice.',
    ],
  },
  {
    num: '10',
    title: 'Intellectual Property',
    body: [
      'The Service, platform, and DeepNano technology are our property. You receive a limited, revocable license during your subscription.',
      'AI-generated code ownership follows your provider\'s terms (typically you own it).',
    ],
  },
  {
    num: '11',
    title: 'Termination',
    body: 'We may suspend or terminate access for violations. You may cancel anytime via account settings.',
  },
  {
    num: '12',
    title: 'Disclaimers and Limitation of Liability',
    body: [
      'THE SERVICE IS PROVIDED "AS IS." WE DISCLAIM ALL WARRANTIES.',
      'IN NO EVENT SHALL OUR LIABILITY EXCEED THE AMOUNTS PAID BY YOU IN THE PAST 12 MONTHS.',
      'We are not liable for AI errors, code issues, downtime, or third-party provider actions (including billing from your BYOK keys).',
    ],
  },
  {
    num: '13',
    title: 'Indemnification',
    body: 'You agree to indemnify us against claims arising from your use, User Content, or violations of these Terms.',
  },
  {
    num: '14',
    title: 'Governing Law',
    body: 'These Terms are governed by the laws of Florida, United States.',
  },
  {
    num: '15',
    title: 'Changes to Terms',
    body: 'We may update these Terms with notice. Continued use constitutes acceptance.',
  },
]

export default function TermsOfService() {
  return (
    <div className="relative z-10 min-h-screen bg-bg-primary text-text-primary">
      {/* Header */}
      <header className="border-b border-border">
        <div className="max-w-[760px] mx-auto px-6 py-6 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2.5 font-extrabold text-xl tracking-tight text-text-primary no-underline">
            <span className="w-[34px] h-[34px] rounded-[9px] bg-gradient-to-br from-accent via-cyan to-green flex items-center justify-center text-sm shadow-[0_0_20px_rgba(108,92,231,0.3)]">
              ⚛
            </span>
            DeepNano
          </a>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-[760px] mx-auto px-6 py-16 md:py-20">
        <h1 className="text-[clamp(2rem,4vw,3rem)] font-extrabold tracking-[-0.02em] mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-text-muted mb-16">
          Effective Date: June 22, 2026
        </p>

        <div className="space-y-10">
          {SECTIONS.map((s) => (
            <section key={s.num}>
              <h2 className="text-lg font-bold mb-3 flex items-start gap-2">
                <span className="text-accent-light font-mono text-sm mt-[5px]">{s.num}.</span>
                {s.title}
              </h2>
              {Array.isArray(s.body) ? (
                <ul className="list-disc list-outside pl-6 space-y-2 text-[0.95rem] text-text-secondary leading-relaxed">
                  {s.body.map((item) => (
                    <li key={item}>{item}</li>
                  ))}
                </ul>
              ) : (
                <p className="text-[0.95rem] text-text-secondary leading-relaxed pl-6">{s.body}</p>
              )}
            </section>
          ))}
        </div>

        <hr className="border-border mt-16 mb-8" />
        <p className="text-sm text-text-muted">
          Contact:{' '}
          <a href="mailto:tyler@tyler.ag" className="text-accent-light no-underline hover:underline">
            tyler@tyler.ag
          </a>
        </p>
      </main>
    </div>
  )
}
